spring:
  application:
    name: cultivation-server

  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?currentSchema=${CULTIVATION_DB_SCHEMA}&stringtype=unspecified
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    type: org.apache.commons.dbcp2.BasicDataSource
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: ${CULTIVATION_DB_SCHEMA}

  cloud:
    kubernetes:
      discovery:
        enabled: ${K8S_DISCOVERY_ENABLED:false}
  servlet:
    multipart:
      max-file-size: 8MB
      max-request-size: 2MB

  rabbitmq:
    host: ${RABBITMQ_HOST}      # 로컬 Docker
    port: ${RABBITMQ_PORT}           # AMQP 포트
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

    publisher-confirm-type: correlated
    publisher-returns: true

    template:
      mandatory: true
      retry:
        enabled: true
        max-retries: 3
        initial-interval: 1s
        multiplier: 2.0
        max-interval: 10s


eureka:
  client:
    enabled: ${EUREKA_ENABLED:false}
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

logging:
  level:
    root: ${LOG_LEVEL:INFO}

minio:
  url: ${MINIO_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET}

influx:
  url: ${INFLUX_URL}
  org: ${INFLUX_ORG}
  bucket: ${INFLUX_BUCKET:sensor-data}
  token: ${INFLUX_TOKEN}
  cloudflare:
    access-client-id: ${CF_ACCESS_CLIENT_ID:}
    access-client-secret: ${CF_ACCESS_CLIENT_SECRET:}
