spring:
  application:
    name: cultivation-server
  config:
    import: optional:file:.env[.properties]
  cloud:
    eureka:
      client:
        enabled: ${EUREKA_ENABLED:false}
    kubernetes:
      discovery:
        enabled: ${K8S_DISCOVERY_ENABLED:false}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?currentSchema=${DB_SCHEMA}&stringtype=unspecified
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    type: org.apache.commons.dbcp2.BasicDataSource

    dbcp2:
      initial-size: 5
      max-total: 5
      max-idle: 5
      min-idle: 5

      test-on-borrow: true
      validation-query: SELECT 1
      pool-prepared-statements: true
      max-open-prepared-statements: 100
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

logging:
  level:
    root: ${LOG_LEVEL:INFO}
server:
  port: 9001