-- This migration intentionally precedes V1 because Flyway executes before Hibernate.
-- It supplies the tables that V1 evolves and seeds on a fresh database.
CREATE TABLE IF NOT EXISTS sensor_type (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type varchar(255),
    value_unit varchar(255)
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_index i
        JOIN pg_class t ON t.oid = i.indrelid
        WHERE t.relname = 'sensor_type'
          AND t.relnamespace = current_schema()::regnamespace
          AND i.indisunique
          AND ARRAY(
              SELECT a.attname
              FROM unnest(i.indkey) WITH ORDINALITY AS key_column(attnum, position)
              JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = key_column.attnum
              ORDER BY key_column.position
          ) = ARRAY['type', 'value_unit']
    ) THEN
        CREATE UNIQUE INDEX uk_sensor_type_type_value_unit ON sensor_type (type, value_unit);
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS mushroom_reference (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mushroom_name_ko varchar(255),
    mushroom_name_en varchar(255),
    mushroom_scientific_name varchar(255),
    created_at timestamp,
    updated_at timestamp
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_index i
        JOIN pg_class t ON t.oid = i.indrelid
        WHERE t.relname = 'mushroom_reference'
          AND t.relnamespace = current_schema()::regnamespace
          AND i.indisunique
          AND ARRAY(
              SELECT a.attname
              FROM unnest(i.indkey) WITH ORDINALITY AS key_column(attnum, position)
              JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = key_column.attnum
              ORDER BY key_column.position
          ) = ARRAY['mushroom_scientific_name']
    ) THEN
        CREATE UNIQUE INDEX uk_mushroom_reference_scientific_name
            ON mushroom_reference (mushroom_scientific_name);
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS mushroom_reference_threshold (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sensor_type_id bigint REFERENCES sensor_type(id),
    mushroom_reference_id bigint REFERENCES mushroom_reference(id),
    threshold_min numeric(10, 4),
    threshold_max numeric(10, 4),
    created_at timestamp,
    updated_at timestamp,
    CONSTRAINT uk_mushroom_reference_threshold_sensor_reference
        UNIQUE (sensor_type_id, mushroom_reference_id)
);
