-- Squashed initialization: current JPA tables plus the final state of the former V0.1 through V5.
-- For a fresh/reset schema only, with no old Flyway history. This is not an in-place upgrade.
-- Former versioned migrations and B5 have been replaced; future changes start at V2.
-- Flyway owns flyway_schema_history; do not create or insert into it here.
-- Use Flyway's configured default schema, not a hard-coded production schema.
-- After Flyway, Hibernate should validate, not create/create-drop and erase the seed data.
-- This is source-controlled initialization, not a backup of production rows or manual DB changes.

CREATE TABLE sensor_type (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type varchar(255),
    value_unit varchar(255),
    CONSTRAINT uk_sensor_type_type_value_unit UNIQUE (type, value_unit)
);

CREATE TABLE mushroom_reference (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mushroom_name_ko varchar(255),
    mushroom_name_en varchar(255),
    mushroom_scientific_name varchar(255),
    created_at timestamp DEFAULT now(),
    updated_at timestamp,
    CONSTRAINT uk_mushroom_reference_scientific_name UNIQUE (mushroom_scientific_name)
);

CREATE TABLE mushroom_reference_threshold (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sensor_type_id bigint REFERENCES sensor_type(id),
    mushroom_reference_id bigint REFERENCES mushroom_reference(id),
    threshold_type varchar(20) NOT NULL,
    threshold_min numeric(10, 4),
    threshold_max numeric(10, 4),
    created_at timestamp DEFAULT now(),
    updated_at timestamp,
    CONSTRAINT uk_mushroom_reference_threshold_sensor_reference_phase
        UNIQUE (sensor_type_id, mushroom_reference_id, threshold_type),
    CONSTRAINT ck_mushroom_reference_threshold_phase
        CHECK (threshold_type IN ('GROWTH', 'HARVEST'))
);

CREATE TABLE cultivation (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    mode varchar(20),
    name varchar(100) NOT NULL,
    cultivation_status varchar(20) NOT NULL,
    started_at timestamp,
    finished_at timestamp,
    deleted_at timestamp,
    created_at timestamp NOT NULL,
    updated_at timestamp NOT NULL,
    mushroom_id bigint NOT NULL REFERENCES mushroom_reference(id),
    CONSTRAINT uk_cultivation_user_name UNIQUE (user_id, name),
    CONSTRAINT ck_cultivation_mode CHECK (mode IN ('GROWTH', 'HARVEST')),
    CONSTRAINT ck_cultivation_status
        CHECK (cultivation_status IN ('CREATED', 'RUNNING', 'FINISHED', 'DELETED'))
);

CREATE INDEX idx_cultivation_status ON cultivation (cultivation_status);

CREATE TABLE cultivation_member (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    role varchar(20) NOT NULL,
    joined_at timestamp NOT NULL,
    cultivation_id bigint NOT NULL REFERENCES cultivation(id),
    CONSTRAINT uk_cultivation_member_cultivation_user UNIQUE (cultivation_id, user_id),
    CONSTRAINT ck_cultivation_member_role CHECK (role IN ('OWNER', 'MANAGER', 'MEMBER'))
);

CREATE INDEX idx_cultivation_member_user_id ON cultivation_member (user_id);

CREATE TABLE cultivation_photo (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_key varchar(500) NOT NULL,
    storage_type varchar(50) NOT NULL,
    uploaded_at timestamp NOT NULL,
    created_at timestamp NOT NULL,
    cultivation_id bigint NOT NULL REFERENCES cultivation(id)
);

CREATE INDEX idx_cultivation_photo_cultivation_id ON cultivation_photo (cultivation_id);

CREATE TABLE harvest (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    harvest_weight numeric(38, 2),
    memo text,
    harvested_at timestamp NOT NULL,
    product_score numeric(38, 2),
    product_grade varchar(10),
    cultivation_id bigint NOT NULL REFERENCES cultivation(id),
    CONSTRAINT uk_harvest_cultivation UNIQUE (cultivation_id),
    CONSTRAINT ck_harvest_product_grade CHECK (product_grade IN ('TOP', 'HIGH', 'MID', 'LOW'))
);

-- cultivation_id is a scalar in these entities; preserve the existing FK policy.
CREATE TABLE cultivation_sensor (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cultivation_id bigint NOT NULL,
    device_eui varchar(255),
    device_model varchar(255),
    device_name varchar(255),
    location varchar(255),
    location_detail varchar(255),
    sensor_status varchar(255),
    created_at timestamp,
    is_deleted boolean NOT NULL DEFAULT false,
    last_measured_at timestamptz,
    monitoring_started_at timestamptz NOT NULL,
    CONSTRAINT uk_cultivation_sensor_cultivation_eui UNIQUE (cultivation_id, device_eui),
    CONSTRAINT ck_cultivation_sensor_status CHECK (sensor_status IN ('ONLINE', 'OFFLINE', 'ERROR'))
);

CREATE TABLE cultivation_sensor_type (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cultivation_sensor_id bigint REFERENCES cultivation_sensor(id),
    sensor_type_id bigint REFERENCES sensor_type(id),
    CONSTRAINT uk_cultivation_sensor_type_sensor_type UNIQUE (cultivation_sensor_id, sensor_type_id)
);

CREATE TABLE environment_setting (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cultivation_id bigint NOT NULL,
    sensor_type_id bigint REFERENCES sensor_type(id),
    threshold_min numeric(10, 4),
    threshold_max numeric(10, 4),
    created_at timestamp,
    updated_at timestamp,
    CONSTRAINT uk_environment_setting_cultivation_sensor_type UNIQUE (cultivation_id, sensor_type_id)
);

-- Use the canonical temperature/light units while preserving the original reference ranges.
INSERT INTO sensor_type (type, value_unit)
VALUES
    ('TEMPERATURE', '°C'),
    ('HUMIDITY', '%'),
    ('CO2', 'ppm'),
    ('LIGHT', 'lux');

INSERT INTO mushroom_reference (mushroom_name_ko, mushroom_name_en, mushroom_scientific_name)
VALUES
    ('느타리버섯', 'Oyster mushroom', 'Pleurotus ostreatus'),
    ('양송이버섯', 'Button mushroom', 'Agaricus bisporus'),
    ('새송이버섯', 'King oyster mushroom', 'Pleurotus eryngii'),
    ('팽이버섯', 'Enoki mushroom', 'Flammulina velutipes'),
    ('표고버섯', 'Shiitake', 'Lentinula edodes');

WITH default_thresholds (
    scientific_name,
    temp_growth_min, temp_growth_max, temp_harvest_min, temp_harvest_max,
    humidity_growth_min, humidity_growth_max, humidity_harvest_min, humidity_harvest_max,
    co2_growth_min, co2_growth_max, co2_harvest_min, co2_harvest_max,
    light_growth_min, light_growth_max, light_harvest_min, light_harvest_max
) AS (
    VALUES
        ('Pleurotus ostreatus', 18.0, 24.0, 13.0, 18.0, 80.0, 90.0, 85.0, 95.0, 800.0, 1500.0, 600.0, 1000.0, 100.0, 500.0, 100.0, 500.0),
        ('Agaricus bisporus', 20.0, 25.0, 15.0, 18.0, 85.0, 95.0, 80.0, 90.0, 1500.0, 2500.0, 800.0, 1200.0, 0.0, 50.0, 0.0, 50.0),
        ('Pleurotus eryngii', 20.0, 24.0, 14.0, 18.0, 85.0, 90.0, 80.0, 90.0, 1200.0, 2000.0, 800.0, 1200.0, 50.0, 200.0, 100.0, 500.0),
        ('Flammulina velutipes', 12.0, 16.0, 7.0, 10.0, 80.0, 90.0, 70.0, 80.0, 2500.0, 3500.0, 2000.0, 3000.0, 50.0, 200.0, 100.0, 500.0),
        ('Lentinula edodes', 20.0, 25.0, 14.0, 20.0, 65.0, 80.0, 80.0, 90.0, 1000.0, 1500.0, 600.0, 1000.0, 50.0, 200.0, 100.0, 500.0)
)
INSERT INTO mushroom_reference_threshold (
    sensor_type_id, mushroom_reference_id, threshold_type, threshold_min, threshold_max
)
SELECT st.id, mr.id, phase.threshold_type, phase.threshold_min, phase.threshold_max
FROM default_thresholds dt
JOIN mushroom_reference mr ON mr.mushroom_scientific_name = dt.scientific_name
CROSS JOIN LATERAL (VALUES
    ('TEMPERATURE', '°C', 'GROWTH', dt.temp_growth_min, dt.temp_growth_max),
    ('TEMPERATURE', '°C', 'HARVEST', dt.temp_harvest_min, dt.temp_harvest_max),
    ('HUMIDITY', '%', 'GROWTH', dt.humidity_growth_min, dt.humidity_growth_max),
    ('HUMIDITY', '%', 'HARVEST', dt.humidity_harvest_min, dt.humidity_harvest_max),
    ('CO2', 'ppm', 'GROWTH', dt.co2_growth_min, dt.co2_growth_max),
    ('CO2', 'ppm', 'HARVEST', dt.co2_harvest_min, dt.co2_harvest_max),
    ('LIGHT', 'lux', 'GROWTH', dt.light_growth_min, dt.light_growth_max),
    ('LIGHT', 'lux', 'HARVEST', dt.light_harvest_min, dt.light_harvest_max)
) AS phase(sensor_type, value_unit, threshold_type, threshold_min, threshold_max)
JOIN sensor_type st ON st.type = phase.sensor_type AND st.value_unit = phase.value_unit;
